/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LInk: typeof import('react-router-dom')['LInk']
  const Link: typeof import('react-router-dom')['Link']
  const useEffect: typeof import('preact/hooks')['useEffect']
  const useParams: typeof import('react-router-dom')['useParams']
  const useState: typeof import('preact/hooks')['useState']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
